name: Codecov

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  # GitHub provider
  test-github:
    name: Test GitHub Provider
    runs-on: ubuntu-latest
    env:
      PASSAGE_CREDS_TEST-GITHUB_DATA_APPID: ${{ secrets.TEST_GITHUB_APP_ID }}
      PASSAGE_CREDS_TEST-GITHUB_DATA_PRIVATEKEYPATH: ../../../creds/github-app.pem
      PRIVATE_KEY_PATH: ${{ github.workspace }}/creds/github-app.pem

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Create creds directory
        run: mkdir -p creds

      - name: Write GitHub private key
        run: echo "${{ secrets.TEST_GITHUB_APP_PRIVATE_KEY }}" > $PRIVATE_KEY_PATH

      - name: Test GitHub provider
        run: |
          go test -v -coverprofile=coverage.out ./pkg/providers/github

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: providers/github/coverage.out
          fail_ci_if_error: true
