name: Codecov

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  # GitHub provider
  test-github:
    name: Test GitHub Provider
    runs-on: ubuntu-latest
    env:
      PASSAGE_CREDS_TESTGITHUB_DATA_APPID: ${{ secrets.TEST_GITHUB_APP_ID }}
      PASSAGE_CREDS_TESTGITHUB_DATA_PRIVATEKEYPATH: ../../../creds/github-app.pem
      PRIVATE_KEY_PATH: ${{ github.workspace }}/creds/github-app.pem

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Create creds directory
        run: |
          mkdir -p creds
          mkdir -p configs
          touch configs/.secret.yml

      - name: Write GitHub private key
        run: echo "${{ secrets.TEST_GITHUB_APP_PRIVATE_KEY }}" > $PRIVATE_KEY_PATH

      - name: Test GitHub provider
        run: |
          go test -v -coverprofile=coverage.out ./pkg/providers/github

      - name: Generate coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.out
          badge: true
          fail_below_min: true
          format: markdown
          output: coverage.md
          thresholds: "60 80" # red <60%, yellow <80%, else green

      - name: Comment coverage report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: coverage.md
