name: Build and Release

on:
  push:
    tags:
      - "v*.*.*" # Run on version tags like v1.0.0
  pull_request:
    branches:
      - main # Adjust if needed

permissions:
  contents: write
  packages: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      # Run ko build for PRs only
      - name: Run ko build (for PR)
        if: github.event_name == 'pull_request'
        uses: ko-build/setup-ko@v0.8

      - name: Build with ko (for PR)
        if: github.event_name == 'pull_request'
        run: ko build --tags pr-${{ github.event.pull_request.number }}

      # Run GoReleaser for tagged releases only
      - name: Run GoReleaser (for tags)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # If you're using GoReleaser Pro, provide the key:
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
